---
sudo: required
dist: trusty

env:
  - ANSIBLE_VERSION=latest

language: python

python: "2.7"

before_install:
  - sudo apt-get update -qq

install:
    - if [ "$ANSIBLE_VERSION" = "latest" ]; then python src/setup.py;fi

script:
  - "cd src"
  - "sudo python main.py"
